extend type Query {
  Posts(filter: PostFilterInput): [Post]
}

type Post {
  id: String!
  username: String
  body: String
  comments: [Comment]
}

type Comment {
  body: String
  username: String,
  createdAt: String
}


# Input
input PostFilterInput {
  id: String,
  username: String
}