extend type Query {
  getPosts(filter: PostFilterInput): [Post]
  getPost(id: ID!): Post
}

type Post {
  id: ID
  username: String
  body: String
  comments: [Comment]
  likes: [Like]
  createdAt: Date
  success: String
  message: String
}

type Comment {
  id: ID
  body: String!
  username: String!,
  createdAt: Date!
}

type Like {
  id: ID
  username: String
  createdAt: Date
}


# Input
input PostFilterInput {
  id: String,
  username: String
}