extend type Query {
  getPosts(filter: PostFilterInput): [Post]
  getPost(id: ID!): Post
}

type Post {
  id: String!
  username: String
  body: String
  comments: [Comment]
}

type Comment {
  body: String
  username: String,
  createdAt: Date
}


# Input
input PostFilterInput {
  id: String,
  username: String
}