extend type Mutation {
  Post: PostOps
}

type PostOps {
  createPost(input: PostInput): createPostResponse
  deletePost(id: ID!): DefaultResponse
  createComment(postId: ID!, body: String!): Post
  deleteComment(postId: ID!, commentId: ID!): DefaultResponse
  likePost(postId: ID!): DefaultResponse
}

input PostInput {
  body: String
}

type createPostResponse {
  body: String
  username: String
  success: String
  message: String
}