extend type Mutation {
  Post: PostOps
}

type PostOps {
  create(input: PostInput): createPostResponse
  delete(id: ID!): DefaultResponse
}

input PostInput {
  body: String
}

type createPostResponse {
  body: String
  username: String
  success: String
  message: String
}