extend type Mutation {
  Post: PostOps
}

type PostOps {
  createPost(input: PostInput): createPostResponse
  deletePost(id: ID!): DefaultResponse
  createComment(postId: ID!, body: String!): Post
  deleteComment(postId: ID!, commentId: ID!): DefaultResponse
  likePost(postId: ID!): DefaultResponse
}

input PostInput {
  body: String!
}

type createPostResponse {
  id: ID
  body: String
  username: String
  createdAt: Date
  likeCount: Int 
  comments: [Comment]
  likes: [Like]
  commentCount: Int
  success: String
  message: String
}